export const companyData = [
  {
    id: 1,
    company_name: "XYZ Company",
    owner_name: "Alice Johnson",
    owner_email: "alice.johnson@example.com",
    owner_phone: "+1-202-555-0143",
    paid: true,
    payment_date: "2025-03-15",
    approve: true,
  },
  {
    id: 2,
    company_name: "Acme Corp",
    owner_name: "Bob Smith",
    owner_email: "bob.smith@example.com",
    owner_phone: "+1-303-555-0124",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 3,
    company_name: "Sunrise Solutions",
    owner_name: "Carla Lee",
    owner_email: "carla.lee@example.com",
    owner_phone: "+1-312-555-0176",
    paid: true,
    payment_date: "2025-04-01",
    approve: true,
  },
  {
    id: 4,
    company_name: "TechNova",
    owner_name: "Daniel Kim",
    owner_email: "daniel.kim@example.com",
    owner_phone: "+1-415-555-0199",
    paid: true,
    payment_date: "2025-01-10",
    approve: true,
  },
  {
    id: 5,
    company_name: "BlueOcean Inc",
    owner_name: "Ella Davis",
    owner_email: "ella.davis@example.com",
    owner_phone: "+1-646-555-0147",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 6,
    company_name: "NextGen Co",
    owner_name: "Franklin Moore",
    owner_email: "frank.moore@example.com",
    owner_phone: "+1-720-555-0134",
    paid: true,
    payment_date: "2025-02-21",
    approve: true,
  },
  {
    id: 7,
    company_name: "Lighthouse Ltd",
    owner_name: "Grace Lee",
    owner_email: "grace.lee@example.com",
    owner_phone: "+1-909-555-0192",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 8,
    company_name: "EcoTech",
    owner_name: "Hector Gomez",
    owner_email: "hector.gomez@example.com",
    owner_phone: "+1-818-555-0181",
    paid: true,
    payment_date: "2025-05-12",
    approve: true,
  },
  {
    id: 9,
    company_name: "BrightIdeas",
    owner_name: "Isla Martin",
    owner_email: "isla.martin@example.com",
    owner_phone: "+1-213-555-0170",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 10,
    company_name: "GreenWorks",
    owner_name: "Jake White",
    owner_email: "jake.white@example.com",
    owner_phone: "+1-305-555-0138",
    paid: true,
    payment_date: "2025-04-18",
    approve: true,
  },
  {
    id: 11,
    company_name: "NovaSpark",
    owner_name: "Karen Black",
    owner_email: "karen.black@example.com",
    owner_phone: "+1-206-555-0155",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 12,
    company_name: "VibeTech",
    owner_name: "Leo Walker",
    owner_email: "leo.walker@example.com",
    owner_phone: "+1-602-555-0149",
    paid: true,
    payment_date: "2025-03-28",
    approve: true,
  },
  {
    id: 13,
    company_name: "NimbleWorks",
    owner_name: "Mia Chen",
    owner_email: "mia.chen@example.com",
    owner_phone: "+1-312-555-0188",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 14,
    company_name: "SkyNet Systems",
    owner_name: "Noah Patel",
    owner_email: "noah.patel@example.com",
    owner_phone: "+1-714-555-0166",
    paid: true,
    payment_date: "2025-01-30",
    approve: true,
  },
  {
    id: 15,
    company_name: "FusionCorp",
    owner_name: "Olivia Green",
    owner_email: "olivia.green@example.com",
    owner_phone: "+1-504-555-0123",
    paid: true,
    payment_date: "2025-02-05",
    approve: true,
  },
  {
    id: 16,
    company_name: "MatrixGroup",
    owner_name: "Peter Evans",
    owner_email: "peter.evans@example.com",
    owner_phone: "+1-713-555-0111",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 17,
    company_name: "ZenithSoft",
    owner_name: "Quinn Foster",
    owner_email: "quinn.foster@example.com",
    owner_phone: "+1-720-555-0177",
    paid: true,
    payment_date: "2025-03-02",
    approve: true,
  },
  {
    id: 18,
    company_name: "BrightPath",
    owner_name: "Ruby Long",
    owner_email: "ruby.long@example.com",
    owner_phone: "+1-215-555-0191",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 19,
    company_name: "CloudNest",
    owner_name: "Samuel Wright",
    owner_email: "samuel.wright@example.com",
    owner_phone: "+1-510-555-0180",
    paid: true,
    payment_date: "2025-04-07",
    approve: true,
  },
  {
    id: 20,
    company_name: "Firefly Media",
    owner_name: "Tina Park",
    owner_email: "tina.park@example.com",
    owner_phone: "+1-917-555-0141",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 21,
    company_name: "CodeCrafters",
    owner_name: "Uma Blake",
    owner_email: "uma.blake@example.com",
    owner_phone: "+1-646-555-0150",
    paid: true,
    payment_date: "2025-05-01",
    approve: true,
  },
  {
    id: 22,
    company_name: "QuantumCore",
    owner_name: "Victor Hall",
    owner_email: "victor.hall@example.com",
    owner_phone: "+1-775-555-0127",
    paid: true,
    payment_date: "2025-03-25",
    approve: true,
  },
  {
    id: 23,
    company_name: "EverTech",
    owner_name: "Wendy Nash",
    owner_email: "wendy.nash@example.com",
    owner_phone: "+1-850-555-0136",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 24,
    company_name: "BrightBridge",
    owner_name: "Xavier Reed",
    owner_email: "xavier.reed@example.com",
    owner_phone: "+1-410-555-0190",
    paid: true,
    payment_date: "2025-04-20",
    approve: true,
  },
  {
    id: 25,
    company_name: "SoftStream",
    owner_name: "Yara Singh",
    owner_email: "yara.singh@example.com",
    owner_phone: "+1-702-555-0178",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 26,
    company_name: "NanoSolutions",
    owner_name: "Zack Bell",
    owner_email: "zack.bell@example.com",
    owner_phone: "+1-312-555-0144",
    paid: true,
    payment_date: "2025-02-17",
    approve: true,
  },
  {
    id: 27,
    company_name: "MetaCore",
    owner_name: "Amber Cruz",
    owner_email: "amber.cruz@example.com",
    owner_phone: "+1-213-555-0169",
    paid: false,
    payment_date: "",
    approve: false,
  },
  {
    id: 28,
    company_name: "OceanWave",
    owner_name: "Brian Ortega",
    owner_email: "brian.ortega@example.com",
    owner_phone: "+1-503-555-0159",
    paid: true,
    payment_date: "2025-01-27",
    approve: true,
  },
  {
    id: 29,
    company_name: "StarLink Systems",
    owner_name: "Clara James",
    owner_email: "clara.james@example.com",
    owner_phone: "+1-907-555-0160",
    paid: true,
    payment_date: "2025-05-10",
    approve: true,
  },
  {
    id: 30,
    company_name: "TerraGroup",
    owner_name: "Derek Shaw",
    owner_email: "derek.shaw@example.com",
    owner_phone: "+1-214-555-0183",
    paid: false,
    payment_date: "",
    approve: false,
  },
];
