export const types = {
  SETFIRSTNAME: "SETFIRSTNAME",
  SETLASTNAME: "SETLASTNAME",
  SETEMAIL: "SETEMAIL",
  SETPHONE: "SETPHONE",
  SETPASSWORD: "SETPASSWORD",
  SETNEWPASSWORD: "SETNEWPASSWORD",
  SETREPEATPASSWORD: "SETREPEATPASSWORD",
  RESET: "RESET",
};
