export const types = {
  SETFIRSTNAME: "SETFIRSTNAME",
  SETLASTNAME: "SETLASTNAME",
  SETEMAIL: "SETEMAIL",
  SETPHONE: "SETPHONE",
  SETPASSWORD: "SETPASSWORD",
  SETNEWPASSWORD: "SETNEWPASSWORD",
  SETREPEATPASSWORD: "SETREPEATPASSWORD",
  GOTOPAGE: "GOTOPAGE",
  NEXTPAGE: "NEXTPAGE",
  PREVPAGE: "PREVPAGE",
  SETSEARCH: "SETSEARCH",
  CREATECOMPANY: "CREATECOMPANY",
  SORT: "SORT",
  RESET: "RESET",
};

export const supplierType = {
  SUPID: "SUPID",
  NAME: "NAME",
  COMPANY: "COMPANY",
  EMAIL: "EMAIL",
  PHONE: "PHONE",
  RESET: "RESET",
};

export const categoryType = {
  CATEGORYNAME: "CATEGORYNAME",
  CATEGORYCODE: "CATEGORYCODE",
  STATUS: "STATUS",
};
