export const userData = [
  {
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "+1-202-555-0143",
    short_address: "123 Maple St",
  },
  {
    name: "Brian Carter",
    email: "brian.carter@example.com",
    phone: "+1-303-555-0167",
    short_address: "456 Oak Ave",
  },
  {
    name: "Cynthia Lee",
    email: "cynthia.lee@example.com",
    phone: "+1-404-555-0189",
    short_address: "789 Pine Rd",
  },
  {
    name: "David Patel",
    email: "david.patel@example.com",
    phone: "+1-212-555-0121",
    short_address: "101 Elm Blvd",
  },
  {
    name: "Ella Thompson",
    email: "ella.thompson@example.com",
    phone: "+1-718-555-0175",
    short_address: "234 Cedar Ln",
  },
  {
    name: "Frank Ramirez",
    email: "frank.ramirez@example.com",
    phone: "+1-415-555-0193",
    short_address: "876 Birch Ct",
  },
  {
    name: "Grace Kim",
    email: "grace.kim@example.com",
    phone: "+1-206-555-0138",
    short_address: "321 Spruce Dr",
  },
  {
    name: "Hector Nguyen",
    email: "hector.nguyen@example.com",
    phone: "+1-617-555-0154",
    short_address: "567 Redwood St",
  },
  {
    name: "Isabel Wright",
    email: "isabel.wright@example.com",
    phone: "+1-602-555-0171",
    short_address: "891 Fir Pl",
  },
  {
    name: "Jake Martinez",
    email: "jake.martinez@example.com",
    phone: "+1-312-555-0119",
    short_address: "654 Aspen Way",
  },
  {
    name: "Kara Brooks",
    email: "kara.brooks@example.com",
    phone: "+1-925-555-0198",
    short_address: "741 Palm Cir",
  },
  {
    name: "Liam Fisher",
    email: "liam.fisher@example.com",
    phone: "+1-210-555-0133",
    short_address: "159 Willow Dr",
  },
  {
    name: "Maya Singh",
    email: "maya.singh@example.com",
    phone: "+1-917-555-0162",
    short_address: "882 Chestnut Ave",
  },
  {
    name: "Noah Clark",
    email: "noah.clark@example.com",
    phone: "+1-303-555-0182",
    short_address: "210 Poplar St",
  },
  {
    name: "Olivia Adams",
    email: "olivia.adams@example.com",
    phone: "+1-310-555-0125",
    short_address: "993 Magnolia Rd",
  },
  {
    name: "Paul Young",
    email: "paul.young@example.com",
    phone: "+1-646-555-0179",
    short_address: "333 Cypress Ln",
  },
  {
    name: "Quinn Howard",
    email: "quinn.howard@example.com",
    phone: "+1-469-555-0114",
    short_address: "787 Hemlock St",
  },
  {
    name: "Rosa Bennett",
    email: "rosa.bennett@example.com",
    phone: "+1-770-555-0158",
    short_address: "178 Beech Ct",
  },
  {
    name: "Sean Edwards",
    email: "sean.edwards@example.com",
    phone: "+1-480-555-0173",
    short_address: "412 Hickory Blvd",
  },
  {
    name: "Tina Morgan",
    email: "tina.morgan@example.com",
    phone: "+1-503-555-0149",
    short_address: "226 Juniper St",
  },
];
